### ISSUE TITLE
Suggestion！！

### ISSUE THREAD

**Issue by JZFamily** [Kiritow/GSock#7]
1， please use namespace

**Comment by JZFamily** [comment]
2，OK  impl class should be rename

**Comment by JZFamily** [comment]
能不能这么搞呀。
sock数据  
操作的  selector之类的里边可以设置首发时间啊，阻塞啊，
创建的     不知道拿出来合不合适
查询的   getpeer之类的

**Comment by Kiritow** [comment]
1. 阻塞和非阻塞是socket的属性，select是用于异步处理的。
2. 设计上socket是延迟创建的, 使用者不需要考虑socket何时创建.
3. getpeer等查询操作对listen端口和UDP socket没有意义, 因此放在使用TCP的`class sock`里

**Comment by JZFamily** [comment]
eummm,你所的很有有道理
